// Mocks generated by Mockito 5.4.6 from annotations
// in nutribunda/test/presentation/providers/quiz_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nutribunda/core/services/quiz_service.dart' as _i3;
import 'package:nutribunda/data/models/quiz_question.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeQuizResult_0 extends _i1.SmartFake implements _i2.QuizResult {
  _FakeQuizResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuizStatistics_1 extends _i1.SmartFake
    implements _i3.QuizStatistics {
  _FakeQuizStatistics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QuizService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizService extends _i1.Mock implements _i3.QuizService {
  MockQuizService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.QuizQuestion>> getRandomQuestions({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomQuestions, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i2.QuizQuestion>>.value(
              <_i2.QuizQuestion>[],
            ),
          )
          as _i4.Future<List<_i2.QuizQuestion>>);

  @override
  _i4.Future<_i2.QuizResult> submitAnswers(
    List<_i2.QuizAnswerSubmission>? answers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitAnswers, [answers]),
            returnValue: _i4.Future<_i2.QuizResult>.value(
              _FakeQuizResult_0(
                this,
                Invocation.method(#submitAnswers, [answers]),
              ),
            ),
          )
          as _i4.Future<_i2.QuizResult>);

  @override
  _i4.Future<void> saveHighScore(int? score, int? totalQuestions) =>
      (super.noSuchMethod(
            Invocation.method(#saveHighScore, [score, totalQuestions]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.HighScore>> getHighScores() =>
      (super.noSuchMethod(
            Invocation.method(#getHighScores, []),
            returnValue: _i4.Future<List<_i2.HighScore>>.value(
              <_i2.HighScore>[],
            ),
          )
          as _i4.Future<List<_i2.HighScore>>);

  @override
  _i4.Future<void> clearHighScores() =>
      (super.noSuchMethod(
            Invocation.method(#clearHighScores, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isHighScore(int? score) =>
      (super.noSuchMethod(
            Invocation.method(#isHighScore, [score]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i3.QuizStatistics> getQuizStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getQuizStatistics, []),
            returnValue: _i4.Future<_i3.QuizStatistics>.value(
              _FakeQuizStatistics_1(
                this,
                Invocation.method(#getQuizStatistics, []),
              ),
            ),
          )
          as _i4.Future<_i3.QuizStatistics>);
}
