// Mocks generated by Mockito 5.4.6 from annotations
// in nutribunda/test/integration/lbs_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:geolocator/geolocator.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:nutribunda/core/services/location_service.dart' as _i2;
import 'package:nutribunda/core/services/maps_launcher_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i2.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> requestLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationPermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Position?> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i3.Future<_i4.Position?>.value(),
          )
          as _i3.Future<_i4.Position?>);

  @override
  _i3.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.LocationPermission> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i3.Future<_i4.LocationPermission>.value(
              _i4.LocationPermission.denied,
            ),
          )
          as _i3.Future<_i4.LocationPermission>);

  @override
  _i3.Future<bool> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [MapsLauncherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapsLauncherService extends _i1.Mock
    implements _i5.MapsLauncherService {
  MockMapsLauncherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String createMapsSearchUrl({
    required double? latitude,
    required double? longitude,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMapsSearchUrl, [], {
              #latitude: latitude,
              #longitude: longitude,
              #category: category,
            }),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#createMapsSearchUrl, [], {
                #latitude: latitude,
                #longitude: longitude,
                #category: category,
              }),
            ),
          )
          as String);

  @override
  _i3.Future<bool> openMapsSearch({
    required double? latitude,
    required double? longitude,
    required String? categoryKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openMapsSearch, [], {
              #latitude: latitude,
              #longitude: longitude,
              #categoryKey: categoryKey,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isGoogleMapsInstalled() =>
      (super.noSuchMethod(
            Invocation.method(#isGoogleMapsInstalled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> openMapAtLocation({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openMapAtLocation, [], {
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
