// Mocks generated by Mockito 5.4.4 from annotations
// in nutribunda/test/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:flutter/foundation.dart' as _i2;
import 'package:geolocator/geolocator.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nutribunda/data/models/user_model.dart' as _i6;
import 'package:nutribunda/data/models/diary_entry.dart' as _i7;
import 'package:nutribunda/data/models/nutrition_summary.dart' as _i8;
import 'package:nutribunda/presentation/providers/auth_provider.dart' as _i9;
import 'package:nutribunda/presentation/providers/diet_plan_provider.dart' as _i10;
import 'package:nutribunda/presentation/providers/food_diary_provider.dart' as _i11;
import 'package:nutribunda/presentation/providers/lbs_provider.dart' as _i12;
import 'package:nutribunda/presentation/providers/profile_provider.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChangeNotifier_0 extends _i1.SmartFake
    implements _i2.ChangeNotifier {
  _FakeChangeNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePosition_1 extends _i1.SmartFake implements _i5.Position {
  _FakePosition_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_2 extends _i1.SmartFake implements _i6.UserModel {
  _FakeUserModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDiaryEntry_3 extends _i1.SmartFake implements _i7.DiaryEntry {
  _FakeDiaryEntry_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNutritionSummary_4 extends _i1.SmartFake implements _i8.NutritionSummary {
  _FakeNutritionSummary_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i9.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  _i6.UserModel? get user => (super.noSuchMethod(
        Invocation.getter(#user),
      ) as _i6.UserModel?);

  @override
  String? get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
      ) as String?);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<bool> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> register(
    String? email,
    String? password,
    String? fullName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            fullName,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DietPlanProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDietPlanProvider extends _i1.Mock implements _i10.DietPlanProvider {
  MockDietPlanProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  double? get bmr => (super.noSuchMethod(
        Invocation.getter(#bmr),
      ) as double?);

  @override
  double? get tdee => (super.noSuchMethod(
        Invocation.getter(#tdee),
      ) as double?);

  @override
  double? get targetCalories => (super.noSuchMethod(
        Invocation.getter(#targetCalories),
      ) as double?);

  @override
  int get steps => (super.noSuchMethod(
        Invocation.getter(#steps),
        returnValue: 0,
      ) as int);

  @override
  double get caloriesBurned => (super.noSuchMethod(
        Invocation.getter(#caloriesBurned),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void calculateBMR() => super.noSuchMethod(
        Invocation.method(#calculateBMR, []),
        returnValueForMissingStub: null,
      );

  @override
  void calculateTDEE() => super.noSuchMethod(
        Invocation.method(#calculateTDEE, []),
        returnValueForMissingStub: null,
      );

  @override
  void updateSteps(int? steps) => super.noSuchMethod(
        Invocation.method(#updateSteps, [steps]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FoodDiaryProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodDiaryProvider extends _i1.Mock implements _i11.FoodDiaryProvider {
  MockFoodDiaryProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i7.DiaryEntry> get entries => (super.noSuchMethod(
        Invocation.getter(#entries),
        returnValue: <_i7.DiaryEntry>[],
      ) as List<_i7.DiaryEntry>);

  @override
  _i8.NutritionSummary get nutritionSummary => (super.noSuchMethod(
        Invocation.getter(#nutritionSummary),
        returnValue: _FakeNutritionSummary_4(
          this,
          Invocation.getter(#nutritionSummary),
        ),
      ) as _i8.NutritionSummary);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LBSProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLBSProvider extends _i1.Mock implements _i12.LBSProvider {
  MockLBSProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Position? get currentPosition => (super.noSuchMethod(
        Invocation.getter(#currentPosition),
      ) as _i5.Position?);

  @override
  bool get isLoadingLocation => (super.noSuchMethod(
        Invocation.getter(#isLoadingLocation),
        returnValue: false,
      ) as bool);

  @override
  String? get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
      ) as String?);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> fetchCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #fetchCurrentLocation,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> searchFacility(String? categoryKey) => (super.noSuchMethod(
        Invocation.method(
          #searchFacility,
          [categoryKey],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProfileProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileProvider extends _i1.Mock implements _i13.ProfileProvider {
  MockProfileProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  _i6.UserModel? get user => (super.noSuchMethod(
        Invocation.getter(#user),
      ) as _i6.UserModel?);

  @override
  String? get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
      ) as String?);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<bool> fetchProfile() => (super.noSuchMethod(
        Invocation.method(
          #fetchProfile,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateProfile({
    String? fullName,
    double? weight,
    double? height,
    int? age,
    bool? isBreastfeeding,
    String? activityLevel,
    String? timezone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #fullName: fullName,
            #weight: weight,
            #height: height,
            #age: age,
            #isBreastfeeding: isBreastfeeding,
            #activityLevel: activityLevel,
            #timezone: timezone,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> uploadProfileImage(_i4.File? imageFile) => (super.noSuchMethod(
        Invocation.method(
          #uploadProfileImage,
          [imageFile],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}